<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>preview</LangVersion>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\ReplayGlitchLogo.ico</ApplicationIcon>
    <AssemblyName>VaultLoop</AssemblyName>
    <RootNamespace>ReplayGlitchGTA</RootNamespace>
    <PlatformTarget>x64</PlatformTarget>
    <Prefer32Bit>false</Prefer32Bit>
    <Deterministic>true</Deterministic>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <GenerateSupportedRuntime>false</GenerateSupportedRuntime>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Assets\ReplayGlitchLogo.png" LogicalName="ReplayGlitchLogo.png" />
    <Reference Include="Microsoft.CSharp" />
  </ItemGroup>
</Project>
